# Generated by Django 5.2.7 on 2025-11-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='objetos_encontrados/')),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACHADO', 'Objeto Achado (Devolvido)'), ('PERDIDO', 'Objeto Perdido (Buscando Dono)')], default='PERDIDO', max_length=10)),
                ('local_encontrado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ache_facil.local')),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
